#from .preprocess_cell2vec import load_data_cell2vec
from .preprocess_internal_cell2vec import load_data_internal_cell2vec

#from .preprocess_cell2vec_cos import load_data_cell2vec_cos
#from .preprocess_internal_cell2vec_cos import load_data_internal_cell2vec_cos

#from .preprocess import load_data
#from .preprocess_internal import load_data_internal

#from .preprocess_cell2vec_cos_notrain import load_data_cell2vec_cos_notrain
#from .preprocess_internal_cell2vec_cos_notrain import load_data_internal_cell2vec_cos_notrain

#from .preprocess_emb import load_data_emb
#from .preprocess_internal_emb import load_data_internal_emb

#from .preprocess_cell2vec_emb import load_data_cell2vec_emb
#from .preprocess_internal_cell2vec_emb import load_data_internal_cell_emb

#from .preprocess_emb_cos import load_data_emb_cos
#from .preprocess_internal_emb_cos import load_data_internal_emb_cos

#from .preprocess_cell2vec_emb_cos import load_data_cell2vec_emb_cos
#from .preprocess_internal_cell2vec_emb_cos import load_data_internal_cell_emb_cos

from .preprocess_nn import load_data_nn
from .preprocess_internal_nn import load_data_internal_nn